[libdefaults]
  default_realm = CLOUDERA.LOCAL
  dns_lookup_realm = false
  dns_lookup_kdc = false
  rdns = false
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true

[realms]
  CLOUDERA.LOCAL = {
    kdc = kdc.cloudera.local
    admin_server = kdc.cloudera.local
  }

[domain_realm]
  .cloudera.local = CLOUDERA.LOCAL
  cloudera.local = CLOUDERA.LOCAL
