[libdefaults]
 default_realm = EXAMPLE.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 rdns = false
 udp_preference_limit = 1
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 EXAMPLE.COM = {
  # Replace localhost with the Docker host if the lab is running on another machine.
  kdc = localhost
  admin_server = localhost
 }

[domain_realm]
 .hadoop.local = EXAMPLE.COM
 hadoop.local = EXAMPLE.COM
